name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: vonMises
        environment-file: environment.yml

    - name: Initialize Conda
      run: |
        conda init bash
        source ~/.bashrc

    - name: Activate Conda environment
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate vonMises

    - name: Build
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate vonMises
        python install.py
        cat build.log
<<<<<<< Updated upstream
        vonMises -m test-data/MATRIX.mat -k A
=======
        vonMises -m test/test-data/MATRIX.mat -k A

    - name: Unittest
      run: |
        conda activate vm
        pytest -s test/unit-test
>>>>>>> Stashed changes

    - name: Code Lint
      run: |
        source /usr/share/miniconda/etc/profile.d/conda.sh
        conda activate vonMises
        ruff version
        ruff format --check .
        ruff check --output-format=github .
