name: Linux Build and Test

on:
  push:
    branches: 
      - master
      - Fix-ci/cd-pipeline
  pull_request:
    branches: 
      - master
      - Fix-ci/cd-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Create Environment
      run: |
        conda env create -f environment.yml

    - name: Build
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        python install.py install
        vonMises -m test/test-data/MATRIX.mat -k A > vonMises.log 2>&1

    - name: Unittest
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        pytest -s test/unit-test

    - name: Code Lint
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        ruff version
        ruff format --check .
        ruff check --output-format=github .

    - name: Archive Logs
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: |
          build.log
          vonMises.log
          test/unit-test.log
          test/*.log
