name: Linux Build and Test

on:
  push:
    branches:
      - master
      - Fix-build
      - Fix-ci/cd-pipeline
      - Fix-unittest
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Create Environment
      run: |
        conda env create -f environment.yml

    - name: Code Lint
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        ruff version
        ruff format --check .
        ruff check --output-format=github .

  build:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Create Environment
      run: |
        conda env create -f environment.yml

    - name: Build
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        python install.py install
        vonMises -m test/test-data/MATRIX.mat -k A > vonMises.log 2>&1

    - name: Archive Build Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-logs
        path: |
          vonMises.log

  unittest:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Create Environment
      run: |
        conda env create -f environment.yml

    - name: Unittest
      run: |
        source $(conda info --base)/etc/profile.d/conda.sh
        conda activate vm
        pytest -s . > test.log 2>&1

    - name: Archive Test Logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-logs
        path: |
          test.log
