name: Windows Build and Test

on:
  push:
    branches: 
      - master
      - Fix-ci/cd-pipeline
  pull_request:
    branches: 
      - master
      - Fix-ci/cd-pipeline

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2

    - name: Create Environment
      run: conda env create -f environment.yml

    - name: Build
      run: |
        conda activate vm
        python install.py
        pip install dist\*
        type build.log
        where eigen.dll
        vonMises -m test\test-data\MATRIX.mat -k A

    - name: Unittest
      run: |
        conda activate vm
        pytest -s test\unit-test

    - name: Code Lint
      run: |
        conda activate vm
        ruff version
        ruff format --check .
        ruff check --output-format=github .
